floyd_algorithm_simon: read_adjacency_matrix.cpp floyd_algorithm_simon.cpp
	mpic++ -g -lmpichfort -o floyd_algorithm_simon floyd_algorithm_simon.cpp read_adjacency_matrix.cpp

all: floyd_algorithm_simon

clean:
	rm floyd_algorithm_simon
