CPP_APPS=Sieve_of_Eratosthenes_v1
CPP_OBJS=
all: ${CPP_APPS}
clean: 
	rm -f ${CPP_APPS}

Sieve_of_Eratosthenes: Sieve_of_Eratosthenes_v1.cpp 
	mpic++ -g -I/usr/include/x86_64-linux-gnu/mpich/ -o  $@ $<